services:
  postgres:
    image: postgres:15
    container_name: devhub_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB_NAME:-devhub_db}
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}

    volumes:
      - postgres_data:/var/lib/postgresql/data

    ports:
      - ${POSTGRES_PORT:-5432}:5432

volumes:
  postgres_data: